FROM node:20 AS build

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci --force

COPY . .

RUN npm run build --prod
FROM nginx:alpine
COPY --from=build /app/dist/frontend/browser/* /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]