version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    container_name: angular_frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    restart: always

  backend:
    build:
      context: ./backend/demo
    container_name: spring_backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/mydb
      - SPRING_DATASOURCE_USERNAME=myuser
      - SPRING_DATASOURCE_PASSWORD=mypassword
    depends_on:
      - mariadb
    

  mariadb:
    image: mariadb:10.7
    container_name: my_mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
